### PR TITLE
Fix order of array elements in GHW

### LINKED ISSUE #53: GHW: array indices are reversed
**Description**

**TL;DR:** When plotting a GHW wave in Surfer, array indices appear reversed (i.e. member at index 0 behaves as member at index N-1 should and vice versa). When connecting to the array members with a standard non-array signal and plotting the signal, the values are indexed correctly. The GHW format itself seems to be fine according to [this GHDL ticket](https://github.com/ghdl/ghdl/issues/2970), and [according to developers of Surfer, this is likely a wellen bug](https://gitlab.com/surfer-project/surfer/-/issues/401#note_2449237727).

I have a BCD counter, which is counting using the following array type:
`type t_bcd_array_debug is array (natural range <>) of unsigned(3 downto 0);`

The BCD counter has a generic number of digits and it is designed so that digit at index 0 is the least significant digit. It's output is:
`o_decimals : out   t_bcd_array_debug(DECIMALS - 1 downto 0)`

The testbench is VUnit driven. I have auxiliary signals dec0, dec1 and dec2 which connect to the output array members (in my case DIGITS = 3).

```
inst_uut : entity work.bcd_counter_debug
        generic map (
            DECIMALS => DIGITS
        )
        port map (
            i_clk      => clk,
            o_decimals => decimals
        );    

    dec0 <= decimals(0);
    dec1 <= decimals(1);
    dec2 <= decimals(2);
```

When I plot dec0, dec1 and dec2 in Surfer, I get expected result (dec0 is the least significant digit). But when I plot the array members themselves, I get reversed order of values (decimals(2) is the least significant digit):

Image

I originally suspected GHW format to be incorrect, but this has been disproven in [this ticket over at GHDL GitHub](https://github.com/ghdl/ghdl/issues/2970). [Surfer developer thinks this is a Wellen bug.](https://gitlab.com/surfer-project/surfer/-/issues/401#note_2449237727)

**How to reproduce?**

The VHDL files for the counter, its testbench and the package are zipped along with the GHW file in this ZIP: [bcd_counter_debug.zip](https://github.com/user-attachments/files/19719187/bcd_counter_debug.zip)

GHDL version 5.0.1

OS Windows 11

Surfer version 0.3.0

### PR DESCRIPTION
**Pull request by oscargus**
Closes #53. 

Loops 0, 1, 2 despite `range` being `IntRange(Downto, 2, 0,)` leading to the wrong names of the array elements. Hence, the solution seems to be to loop 2, 1, 0 instead.

### CODE REVIEW

File: wellen/tests/ghw.rs [hunk 1]
```diff
@@ -217,3 +217,46 @@ fn test_issue_35_ghw_failed_to_parse_rtik() {
...
+    let var_id = h.lookup_var(&["bcd_counter_debug_tb"], &"dec0").unwrap();
+    let signal_ref = h[var_id].signal_ref();
+
+    let signal = wave.get_signal(signal_ref).unwrap();
+    let mut values2 = vec![];
+    for (_, value) in signal.iter_changes() {
+        values2.push(value.to_bit_string().unwrap());
+    }
+
+    assert_eq!(values, values2);
```
Comment (ekiwi) [inline wellen/tests/ghw.rs:261]: Can you please add a comment explaining what you are testing for?

File: wellen/src/ghw/hierarchy.rs [hunk 2]
```diff
@@ -1545,10 +1543,22 @@ impl IntRange {
...
+            RangeDir::Downto => self.2,
+        }
+    }
+
+    fn end(&self) -> i64 {
+        match self.0 {
+            RangeDir::To => self.2,
+            RangeDir::Downto => self.1,
+        }
+    }
```
Comment (ekiwi) [inline wellen/src/ghw/hierarchy.rs:1558]: Could you add some unittests inside this file to test this new functionality?

So, add something like this to the end of `hierarchy.rs`:

```rs
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_int_range() {
       // TODO: create some ranges and test the `start`, `end` and `range` functionality
    }
```

**Review by ekiwi — CHANGES_REQUESTED** [review]
This looks good. Please add the comment to the existing test and the unit tests I ask for below:

File: wellen/src/ghw/hierarchy.rs (hunk 2 above)
Comment (oscargus) [reply wellen/src/ghw/hierarchy.rs:1558]: Sure! (I pushed a new version with first comment only before seeing this...)

Not sure how to handle empty ranges though (1 to 0, 0 downto 1). Nor if it matters in practice. I guess `start` and `end` doesn't really make sense then. But `len` should probably clamp to 0?

**Review by ekiwi — APPROVED** [review]
Awesome! Thanks!
